version: '3.8'

services:

  app_db:
    image: postgres:15
    container_name: library-bot-postgresql
    restart: "unless-stopped"
    hostname: postgres
    env_file:
      - .env-non-dev
    ports:
      - "5433:5432"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 30s
        timeout: 10s
        retries: 5

  app_redis:
    image: redis:7.0-alpine
    restart: "unless-stopped"
    hostname: redis
    container_name: library-bot-redis
    command:
      - 'redis-server'
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    container_name: library-bot
    image: library-bot
    restart: "unless-stopped"
    env_file:
      - .env-non-dev
    build:
      context: .
    command: sh -c "alembic upgrade head"
    volumes:
      - .:/code
    depends_on:
      - app_db
      - app_redis
    ports:
      - 8000:8000

volumes:
  app_pg_data:
  redis-data:


networks:
  default:
    name: app_main